server:
  port: 10000
spring:
  application:
    name: config-client
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: admin
      password: 123456
management:
  security:
    enabled: false #刷新时，关闭安全验证